name = "conformance-authrim-op-discovery"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

# KV Namespaces

# D1 Databases

# R2 Buckets

# Durable Objects Bindings
[[durable_objects.bindings]]
name = "KEY_MANAGER"
class_name = "KeyManager"
script_name = "conformance-authrim-shared"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiterCounter"
script_name = "conformance-authrim-shared"

# Environment variables
# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "conformance-authrim-users-db"
database_id = "92847b63-125e-4252-b189-3402895addb4"

[vars]
ISSUER_URL = "https://conformance.authrim.com"
UI_BASE_URL = "https://conformance.authrim.com"
TOKEN_EXPIRY = "3600"
CODE_EXPIRY = "120"
STATE_EXPIRY = "300"
NONCE_EXPIRY = "300"
REFRESH_TOKEN_EXPIRY = "2592000"
KEY_ID = "dev-key-1763802897-a5qa"
ALLOW_HTTP_REDIRECT = "false"
OPEN_REGISTRATION = "false"
TRUSTED_DOMAINS = "www.certification.openid.net"

[[routes]]
pattern = "conformance.authrim.com/.well-known/*"
zone_name = "authrim.com"
