name = "conformance-authrim-op-management"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

# KV Namespaces
[[kv_namespaces]]
binding = "CLIENTS"
id = "ed309880b5ac4dd8b13cf6b5473338e7"

[[kv_namespaces]]
binding = "INITIAL_ACCESS_TOKENS"
id = "c822f7afb2424fdaa3989d97e6530f36"

[[kv_namespaces]]
binding = "SETTINGS"
id = "61f8e90a995544ae88878684f0a19f12"


# D1 Databases
[[d1_databases]]
binding = "DB"
database_name = "conformance-authrim-users-db"
database_id = "92847b63-125e-4252-b189-3402895addb4"


# R2 Buckets

# Durable Objects Bindings
[[durable_objects.bindings]]
name = "KEY_MANAGER"
class_name = "KeyManager"
script_name = "conformance-authrim-shared"

[[durable_objects.bindings]]
name = "REFRESH_TOKEN_ROTATOR"
class_name = "RefreshTokenRotator"
script_name = "conformance-authrim-shared"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiterCounter"
script_name = "conformance-authrim-shared"

[[durable_objects.bindings]]
name = "SESSION_STORE"
class_name = "SessionStore"
script_name = "conformance-authrim-shared"

# Environment variables
[vars]
ISSUER_URL = "https://conformance.authrim.com"
UI_BASE_URL = "https://conformance.authrim.com"
TOKEN_EXPIRY = "3600"
CODE_EXPIRY = "120"
STATE_EXPIRY = "300"
NONCE_EXPIRY = "300"
REFRESH_TOKEN_EXPIRY = "2592000"
KEY_ID = "dev-key-1763802897-a5qa"
ALLOW_HTTP_REDIRECT = "false"
OPEN_REGISTRATION = "false"
TRUSTED_DOMAINS = "www.certification.openid.net"

[[routes]]
pattern = "conformance.authrim.com/register"
zone_name = "authrim.com"

[[routes]]
pattern = "conformance.authrim.com/introspect"
zone_name = "authrim.com"

[[routes]]
pattern = "conformance.authrim.com/revoke"
zone_name = "authrim.com"
